variables:
  GIT_SUBMODULE_STRATEGY: "normal"

stages:
  - build

make:ascent:
  stage: build
  tags:
    - batch
  only:
    - web
    variables:
      - $ECP_MIRROR == "ASCENT"
  variables:
    SCHEDULER_PARAMETERS: "-P CSC390 -W 10 -nnodes 1 -alloc_flags gpumps"
  script:
    - module load numactl hwloc cuda
    - ./autogen.sh
    - ./configure --enable-cuda
    - make -j
    - make check VERBOSE=1
  artifacts:
    when: on_failure
    paths:
      - tests/test-suite.log
      - config.log

make:theta-batch:
  stage: build
  tags:
    - ecp-theta
    - batch
  only:
    refs:
      - master
      - staging
    variables:
      - $ECP_MIRROR == "THETA"
  variables:
    PROJECT_SERVICE_USER: "cscstss"
    SCHEDULER_PARAMETERS: "-A CSC250STPR19 -n 1 -t 20 -q debug-flat-quad"
    CC: "icc"
    CFLAGS: "-xKNL"
    LDFLAGS: "-qopenmp-link=static"
  script:
    - ./autogen.sh
    - ./configure --host=x86_64
    - make
    - make check-programs
    - aprun make check VERBOSE=1
  artifacts:
    when: on_failure
    paths:
      - tests/*.log
      - doc/tutorials/*.log
      - benchmarks/*.log
      - config.log
