stages:
  - build

make:generic:
  stage: build
  script:
    - ./autogen.sh
    - mkdir build
    - ./configure --prefix=`pwd`/build
    - make
    - make install
    - make check
  artifacts:
    when: on_failure
    paths:
      - tests/*.log
  except:
    - /^wip.*/
    - /^WIP.*/

make:knl:
  stage: build
  script:
    - source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
    - ./autogen.sh
    - mkdir build
    - CC=icc CFLAGS="-mkl -xhost" ./configure --prefix=`pwd`/build --enable-benchmarks
    - make -j64
    - make install
    - make check
  artifacts:
    when: on_failure
    paths:
      - tests/*.log
  except:
    - /^wip.*/
    - /^WIP.*/
  tags:
    - knl
