variables:
  ARGOPKGS : "https://xgitlab.cels.anl.gov/argo/argopkgs/-/archive/master/argopkgs-master.tar.gz"

stages:
  - style
  - build
  - docs
  - release

repoquality:
  stage: style
  script:
    - nix run -f "$ARGOPKGS" repoquality --command repoquality
  tags:
    - integration

checkpatch:
  stage: style
  tags:
    - integration
  script:
    - nix run -f "$ARGOPKGS" checkpatch --command checkpatch.pl

make:generic:
  stage: build
  except:
    - /^wip.*/
    - /^WIP.*/
  script:
    - ./autogen.sh
    - mkdir build
    - ./configure --prefix=`pwd`/build
    - make
    - make check
    - make install
  artifacts:
    when: on_failure
    paths:
      - tests/*.log

make:knl:
  stage: build
  except:
    - /^wip.*/
    - /^WIP.*/
  tags:
    - knl
  script:
    - source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
    - ./autogen.sh
    - mkdir build
    - CC=icc CFLAGS="-mkl -xhost" ./configure --prefix=`pwd`/build --enable-benchmarks
    - make -j64
    - make check
    - make install
  artifacts:
    when: on_failure
    paths:
      - tests/*.log

readthedocs:
  stage: docs
  when: on_success
  only:
    - master
    - /v[0-9]+\.[0-9]+\.x/
  tags:
    - integration
  script:
    - nix run nixpkgs.curl -c curl -X POST -d "branch=$CI_COMMIT_REF_NAME" -d "token=$READTHEDOCS_TOKEN" https://readthedocs.org/api/v2/webhook/argo-aml/83161/

dist:
  stage: release
  when: on_success
  only:
    - tags
  tags:
    - integration    
  script:
    - nix-build "$ARGOPKGS" -A aml-dist --arg aml-src ./.
    - nix run nixpkgs.bash -c ./release.sh CREATE $CI_JOB_ID $CI_PROJECT_ID $RELEASE_TOKEN $CI_COMMIT_REF_NAME
  artifacts:
    when: on_success
    paths:
      - result/*.tar.gz
      - CHECKSUM
    expire_in: 1000y

