variables:
  ARGOPKGS : "https://xgitlab.cels.anl.gov/argo/argopkgs/-/archive/master/argopkgs-master.tar.gz"
  DEFAULT_MERGE_TARGET: "origin/staging"

stages:
  - style
  - build
  - docs
  - release

repoquality:
  stage: style
  except:
    - /^wip.*/
    - /^WIP.*/
  script:
    - git ls-files '*.c' '*.h' | grep -vE "benchmarks" > .repoquality
    - nix run -f "$ARGOPKGS" repoquality --command repoquality
  tags:
    - nix
    - kvm
  artifacts:
    when: on_failure
    paths:
      - .repoquality

clang-format:
  stage: style
  except:
    - /^wip.*/
    - /^WIP.*/
  tags:
    - nix
    - kvm
  script:
    - rm -f clang-format-diff
    - target=$(git rev-parse $DEFAULT_MERGE_TARGET)
    - nix-shell "$ARGOPKGS" -A ci.aml-format --run "git-clang-format --quiet --diff $target > clang-format-diff"
    - lint=$(grep -v --color=never "no modified files to format" clang-format-diff || true)
    - if [ ! -z "$lint" ]; then echo "format errors, inspect the clang-format-diff artifact for info"; exit 1; else exit 0; fi
  artifacts:
    when: on_failure
    paths:
      - ./clang-format-diff
    expire_in: 1 week

style:docs:
  stage: style
  except:
    - /^wip.*/
    - /^WIP.*/
  tags:
    - nix
    - kvm
  script:
    - |
      nix-shell "$ARGOPKGS" -A aml-dist --arg aml-src ./. --run bash <<< '
        ./autogen.sh
        mkdir build
        ./configure --prefix=`pwd`/build --enable-docs
        make install-data
      '
  artifacts:
    when: on_failure
    paths:
      - config.log

make:generic:
  tags:
    - nix
    - kvm
  stage: build
  except:
    - /^wip.*/
    - /^WIP.*/
  variables:
    CFLAGS: "-std=c99 -pedantic -Wall -Wextra -Werror -Wno-unused-but-set-parameter"
  script:
    - |
      nix-shell "$ARGOPKGS" -A aml --arg aml-src ./. --run bash <<< '
        ./autogen.sh
        mkdir build
        ./configure --prefix=`pwd`/build
        make
        make check
        make install
      '
  artifacts:
    when: on_failure
    paths:
      - config.log
      - tests/*.log

make:out-of-tree:
  tags:
    - nix
    - kvm
  stage: build
  except:
    - /^wip.*/
    - /^WIP.*/
  variables:
    CFLAGS: "-std=c99 -pedantic -Wall -Wextra -Werror -Wno-unused-but-set-parameter"
  script:
    - |
      nix-shell "$ARGOPKGS" -A aml --arg aml-src ./. --run bash <<< '
        ./autogen.sh
        mkdir out
        cd out
        mkdir build
        ../configure --prefix=`pwd`/build
        make
        make check
      '
  artifacts:
    when: on_failure
    paths:
      - config.log
      - tests/*.log

make:knl:
  stage: build
  except:
    - /^wip.*/
    - /^WIP.*/
  tags:
    - knl
  script:
    - source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
    - ./autogen.sh
    - mkdir build
    - CC=icc CFLAGS="-mkl -xhost" ./configure --prefix=`pwd`/build --enable-benchmarks
    - make -j64
    - make -C tests check
    - make install
  artifacts:
    when: on_failure
    paths:
      - config.log
      - tests/*.log

readthedocs:
  stage: docs
  when: on_success
  only:
    - staging
    - master
    - /v[0-9]+\.[0-9]+\.x/
  tags:
    - nix
    - kvm
  environment:
    name: rtd/$CI_COMMIT_REF_NAME
    url: https://argo-aml.readthedocs.io/en/$CI_COMMIT_REF_NAME
  script:
    - nix run nixpkgs.curl -c curl -X POST -d "branches=$CI_COMMIT_REF_NAME" -d "token=$READTHEDOCS_TOKEN" https://readthedocs.org/api/v2/webhook/argo-aml/83161/

