variables:
  ARGOPKGS : "https://xgitlab.cels.anl.gov/argo/argopkgs/-/archive/master/argopkgs-master.tar.gz"

stages:
  - style
  - build
  - release

make:generic:
  stage: build
  script:
    - ./autogen.sh
    - mkdir build
    - ./configure --prefix=`pwd`/build
    - make
    - make check
    - make install
  artifacts:
    when: on_failure
    paths:
      - tests/*.log
  except:
    - /^wip.*/
    - /^WIP.*/

make:knl:
  stage: build
  script:
    - source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
    - ./autogen.sh
    - mkdir build
    - CC=icc CFLAGS="-mkl -xhost" ./configure --prefix=`pwd`/build --enable-benchmarks
    - make -j64
    - make check
    - make install
  artifacts:
    when: on_failure
    paths:
      - tests/*.log
  except:
    - /^wip.*/
    - /^WIP.*/
  tags:
    - knl

repoquality:
  stage: style
  script:
    - nix run -f "$ARGOPKGS" repoquality --command repoquality
  tags:
    - integration

checkpatch:
  stage: style
  script:
    - nix run -f "$ARGOPKGS" checkpatch --command checkpatch.pl

readthedocs:
  stage: release
  when: on_success
  only:
    - master
    - /v\.[0-9]+\.[0-9]+\.[0-9]+/
  script:
    - nix run nixpkgs.curl -c curl -X POST -d "branch=$CI_COMMIT_REF_NAME" -d "token=$READTHEDOCS_TOKEN" https://readthedocs.org/api/v2/webhook/argo-aml/83161/
