variables:
  ARGOPKGS : "https://xgitlab.cels.anl.gov/argo/argopkgs/-/archive/master/argopkgs-master.tar.gz"

stages:
  - style
  - build
  - docs
  - release

repoquality:
  stage: style
  except:
    - /^wip.*/
    - /^WIP.*/
  script:
    - git ls-files *.c *.h | grep -v -e benchmarks > .repoquality
    - nix run -f "$ARGOPKGS" repoquality --command repoquality
  tags:
    - nix
    - kvm
  artifacts:
    when: on_failure
    paths:
      - .repoquality

checkpatch:
  stage: style
  except:
    - /^wip.*/
    - /^WIP.*/
  tags:
    - nix
    - kvm
  script:
    - nix run -f "$ARGOPKGS" checkpatch --command checkpatch.pl --ignore TRAILING_SEMICOLON --ignore MULTISTATEMENT_MACRO_USE_DO_WHILE include/aml/utils/inner-malloc.h
    - git ls-files *.c *.h | grep -v -e benchmarks | grep -v -e inner-malloc >> .checkpatch.conf
    - nix run -f "$ARGOPKGS" checkpatch --command checkpatch.pl

style:docs:
  stage: style
  except:
    - /^wip.*/
    - /^WIP.*/
  tags:
    - nix
    - kvm
  script:
    - |
      nix-shell "$ARGOPKGS" -A aml-dist --arg aml-src ./. --run bash << EOF
      ./autogen.sh
      mkdir build
      ./configure --prefix=`pwd`/build --enable-docs
      make install-data
      EOF
  artifacts:
    when: on_failure
    paths:
      - config.log

make:generic:
  tags:
    - knl
  stage: build
  except:
    - /^wip.*/
    - /^WIP.*/
  variables:
    CFLAGS: "-std=c99 -pedantic -Wall -Wextra -Werror -Wno-unused-but-set-parameter"
  script:
    - ./autogen.sh
    - mkdir build
    - ./configure --prefix=`pwd`/build
    - make
    - make check
    - make install
  artifacts:
    when: on_failure
    paths:
      - config.log
      - tests/*.log

make:out-of-tree:
  tags:
    - knl
  stage: build
  except:
    - /^wip.*/
    - /^WIP.*/
  variables:
    CFLAGS: "-std=c99 -pedantic -Wall -Wextra -Werror -Wno-unused-but-set-parameter"
  script:
    - ./autogen.sh
    - mkdir out
    - cd out
    - mkdir build
    - ../configure --prefix=`pwd`/build
    - make
    - make check
  artifacts:
    when: on_failure
    paths:
      - config.log
      - tests/*.log

make:knl:
  stage: build
  except:
    - /^wip.*/
    - /^WIP.*/
  tags:
    - knl
  script:
    - source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
    - ./autogen.sh
    - mkdir build
    - CC=icc CFLAGS="-mkl -xhost" ./configure --prefix=`pwd`/build --enable-benchmarks
    - make -j64
    - make check
    - make install
  artifacts:
    when: on_failure
    paths:
      - config.log
      - tests/*.log

readthedocs:
  stage: docs
  when: on_success
  only:
    - staging
    - master
    - /v[0-9]+\.[0-9]+\.x/
  tags:
    - nix
    - kvm
  environment:
    name: rtd/$CI_COMMIT_REF_NAME
    url: https://argo-aml.readthedocs.io/en/$CI_COMMIT_REF_NAME
  script:
    - nix run nixpkgs.curl -c curl -X POST -d "branches=$CI_COMMIT_REF_NAME" -d "token=$READTHEDOCS_TOKEN" https://readthedocs.org/api/v2/webhook/argo-aml/83161/

