variables:
  ARGOPKGS : "https://xgitlab.cels.anl.gov/argo/argopkgs/-/archive/master/argopkgs-master.tar.gz"

stages:
  - build

make:generic:
  stage: build
  script:
    - ./autogen.sh
    - mkdir build
    - ./configure --prefix=`pwd`/build
    - make
    - make check
    - make install
  artifacts:
    when: on_failure
    paths:
      - tests/*.log
  except:
    - /^wip.*/
    - /^WIP.*/

make:knl:
  stage: build
  script:
    - source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
    - ./autogen.sh
    - mkdir build
    - CC=icc CFLAGS="-mkl -xhost" ./configure --prefix=`pwd`/build --enable-benchmarks
    - make -j64
    - make check
    - make install
  artifacts:
    when: on_failure
    paths:
      - tests/*.log
  except:
    - /^wip.*/
    - /^WIP.*/
  tags:
    - knl

repoquality:
  stage: build
  script:
    - nix run -f "$ARGOPKGS" repoquality --command repoquality
  tags:
    - integration
