make  arena_jemalloc vector tiling binding linux_mbind linux_mmap linux_manager area_linux area_posix dma_linux_seq dma_linux_par scratch_seq scratch_par stream_add_pth_st stream_add_omp_st stream_add_omp_mt matrix_mult_omp
make[1]: Entering directory `/home/suchy/aml/tests'
make[1]: `arena_jemalloc' is up to date.
make[1]: `vector' is up to date.
make[1]: `tiling' is up to date.
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT binding.o -MD -MP -MF .deps/binding.Tpo -c -o binding.o binding.c
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT linux_mbind.o -MD -MP -MF .deps/linux_mbind.Tpo -c -o linux_mbind.o linux_mbind.c
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT linux_mmap.o -MD -MP -MF .deps/linux_mmap.Tpo -c -o linux_mmap.o linux_mmap.c
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT linux_manager.o -MD -MP -MF .deps/linux_manager.Tpo -c -o linux_manager.o linux_manager.c
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT area_linux.o -MD -MP -MF .deps/area_linux.Tpo -c -o area_linux.o area_linux.c
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT area_posix.o -MD -MP -MF .deps/area_posix.Tpo -c -o area_posix.o area_posix.c
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT dma_linux_seq.o -MD -MP -MF .deps/dma_linux_seq.Tpo -c -o dma_linux_seq.o dma_linux_seq.c
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT dma_linux_par.o -MD -MP -MF .deps/dma_linux_par.Tpo -c -o dma_linux_par.o dma_linux_par.c
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT scratch_seq.o -MD -MP -MF .deps/scratch_seq.Tpo -c -o scratch_seq.o scratch_seq.c
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT scratch_par.o -MD -MP -MF .deps/scratch_par.Tpo -c -o scratch_par.o scratch_par.c
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT stream_add_pth_st.o -MD -MP -MF .deps/stream_add_pth_st.Tpo -c -o stream_add_pth_st.o stream_add_pth_st.c
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT stream_add_omp_st.o -MD -MP -MF .deps/stream_add_omp_st.Tpo -c -o stream_add_omp_st.o stream_add_omp_st.c

gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT matrix_mult_omp.o -MD -MP -MF .deps/matrix_mult_omp.Tpo -c -o matrix_mult_omp.o matrix_mult_omp.c

gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../src    -fopenmp -I../src -g -O2 -MT stream_add_omp_mt.o -MD -MP -MF .deps/stream_add_omp_mt.Tpo -c -o stream_add_omp_mt.o stream_add_omp_mt.c
mv -f .deps/binding.Tpo .deps/binding.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o binding binding.o  -lnuma 
mv -f .deps/area_posix.Tpo .deps/area_posix.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o area_posix area_posix.o  -lnuma 
mv -f .deps/linux_manager.Tpo .deps/linux_manager.Po
mv -f .deps/linux_mmap.Tpo .deps/linux_mmap.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o linux_manager linux_manager.o  -lnuma 
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o linux_mmap linux_mmap.o  -lnuma 
mv -f .deps/dma_linux_seq.Tpo .deps/dma_linux_seq.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o dma_linux_seq dma_linux_seq.o  -lnuma 
mv -f .deps/dma_linux_par.Tpo .deps/dma_linux_par.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o dma_linux_par dma_linux_par.o  -lnuma 
mv -f .deps/linux_mbind.Tpo .deps/linux_mbind.Po
mv -f .deps/area_linux.Tpo .deps/area_linux.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o linux_mbind linux_mbind.o  -lnuma 
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o area_linux area_linux.o  -lnuma 
mv -f .deps/scratch_par.Tpo .deps/scratch_par.Po
mv -f .deps/scratch_seq.Tpo .deps/scratch_seq.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o scratch_par scratch_par.o  -lnuma 
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o scratch_seq scratch_seq.o  -lnuma 
mv -f .deps/stream_add_omp_mt.Tpo .deps/stream_add_omp_mt.Po
mv -f .deps/stream_add_pth_st.Tpo .deps/stream_add_pth_st.Po

mv -f .deps/stream_add_omp_st.Tpo .deps/stream_add_omp_st.Po

mv -f .deps/matrix_mult_omp.Tpo .deps/matrix_mult_omp.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o stream_add_omp_mt stream_add_omp_mt.o  -lnuma 
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o stream_add_pth_st stream_add_pth_st.o  -lnuma 
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o stream_add_omp_st stream_add_omp_st.o  -lnuma 

/bin/sh/ ../libtool --tag=CC   --mode=link gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../src/libaml.la ../jemalloc/lib/libjemalloc-aml.so  -o matrix_mult_omp matrix_mult_omp.o -lnuma

libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/binding binding.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/area_posix area_posix.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/linux_manager linux_manager.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/linux_mmap linux_mmap.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/dma_linux_seq dma_linux_seq.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/dma_linux_par dma_linux_par.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/linux_mbind linux_mbind.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/area_linux area_linux.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/scratch_par scratch_par.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/scratch_seq scratch_seq.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/stream_add_omp_mt stream_add_omp_mt.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib

libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/matrix_mult_omp matrix_mult_omp.o ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib

libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/stream_add_omp_st stream_add_omp_st.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
libtool: link: gcc -std=gnu99 -fopenmp -I../src -g -O2 -fopenmp ../jemalloc/lib/libjemalloc-aml.so -o .libs/stream_add_pth_st stream_add_pth_st.o  ../src/.libs/libaml.so -L../jemalloc/lib/ -ljemalloc-aml -lnuma -fopenmp -Wl,-rpath -Wl,/home/suchy/aml/build/lib
make[1]: Leaving directory `/home/suchy/aml/tests'
make  check-TESTS
make[1]: Entering directory `/home/suchy/aml/tests'
make[2]: Entering directory `/home/suchy/aml/tests'
PASS: tiling
PASS: arena_jemalloc
PASS: vector
PASS: binding
PASS: linux_mbind
PASS: area_posix
PASS: dma_linux_seq
PASS: linux_manager
PASS: area_linux
PASS: linux_mmap
PASS: scratch_par
PASS: dma_linux_par
PASS: scratch_seq
PASS: stream_add_pth_st
PASS: stream_add_omp_st
PASS: matrix_mult_omp
PASS: stream_add_omp_mt
make[3]: Entering directory `/home/suchy/aml/tests'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/home/suchy/aml/tests'
============================================================================
Testsuite summary for aml 0.0.1
============================================================================
# TOTAL: 16
# PASS:  16
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[2]: Leaving directory `/home/suchy/aml/tests'
make[1]: Leaving directory `/home/suchy/aml/tests'
