################################################################################
# Copyright 2019 UChicago Argonne, LLC.
# (c.f. AUTHORS, LICENSE)
# 
# This file is part of the AML project.
# For more info, see https://xgitlab.cels.anl.gov/argo/aml
# 
# SPDX-License-Identifier: BSD-3-Clause
################################################################################

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import subprocess

# Generate doxygen first if in read the docs.
read_the_docs = os.environ.get('READTHEDOCS', None) == 'True'
if read_the_docs:
    subprocess.call('doxygen aml.doxy', shell=True)
    # Readthedocs doxygen version is too old to copy images when building xml
    subprocess.call('cp img/*png build-doxygen/xml/', shell=True)
 
# -- General configuration ---------------------------------------------------

# The language for content autogenerated by Sphinx.
language = 'C'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["breathe"]

# Add any paths that contain templates here, relative to this directory.
templates_path = []

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# ensure that the master file is index.
# mostly needed because the sphinx version on RTD expects a contents.rst
# instead.
master_doc = 'index'

# -- Project information -----------------------------------------------------

project   = 'AML'
copyright = 'Copyright 2019 UChicago Argonne, LLC'
author    = 'Swann Perarnau, Kamil Iskra, Brian Suchy, Valentin Reis, Nicolas Denoyelle'
release   = '0.1.0'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
if read_the_docs:
    html_theme = 'default'
else:
    html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

breathe_projects = {"aml": "build-doxygen/xml"}
breathe_default_project = "aml"
