variables:
  NMC_FE1_SLURM_PARAMETERS: "--nodes=1 --partition=ecp-p9-4v100"
  ANL_THETA_PROJECT_SERVICE_USER: "cscstss"
  ANL_THETA_SCHEDULER_PARAMETERS: "-A CSC250STPR19 -n 1 -t 20 -q debug-flat-quad"
  GIT_SUBMODULE_STRATEGY: "normal"

stages:
  - build

nmc:batch:env:
  stage: build
  tags:
    - nmc
  only:
    refs:
      - master
      - staging
    variables:
      - $ECP_MIRROR == "NMC"
  script:
    - uname -a
    - module avail
    - lspci
    - module load hwloc numactl cuda
    - module avail
    - lstopo
    - env
    - which gcc
    - gcc --version
    - compgen -c gcc

make:nmc-cuda-check:
  stage: build
  tags:
    - nmc
  only:
    refs:
      - master
      - staging
    variables:
      - $ECP_MIRROR == "NMC"
  script:
    - module load numactl hwloc cuda
    - env | grep -i cuda
    - cat /proc/self/status
    - ./autogen.sh
    - ./configure
    - make -j
    - make check VERBOSE=1
  artifacts:
    when: on_failure
    paths:
      - tests/test-suite.log
      - config.log

make:nmc-cuda-home:
  stage: build
  tags:
    - nmc
  only:
    refs:
      - master
      - staging
    variables:
      - $ECP_MIRROR == "NMC"
  script:
    - module load numactl hwloc cuda
    - env | grep -i cuda
    - ./autogen.sh
    - ./configure --with-cuda=$CUDA_HOME
    - make -j
    - make check VERBOSE=1
  artifacts:
    when: on_failure
    paths:
      - tests/test-suite.log
      - config.log

make:theta-batch:
  stage: build
  tags:
    - ecp-theta
    - batch
  only:
    refs:
      - master
      - staging
    variables:
      - $ECP_MIRROR == "THETA"
  variables:
    CC: "icc"
    CFLAGS: "-xKNL"
    LDFLAGS: "-qopenmp-link=static"
  script:
    - ./autogen.sh
    - ./configure --host=x86_64
    - make
    - make check-programs
    - aprun make check VERBOSE=1
  artifacts:
    when: on_failure
    paths:
      - tests/*.log
      - doc/tutorials/*.log
      - benchmarks/*.log
      - config.log
